/* version.h -- Autogenerated! Do not edit. */

#ifndef __INCLUDE_NUTTX_VERSION_H
#define __INCLUDE_NUTTX_VERSION_H

#define CONFIG_VERSION_STRING "10.2.0"
#define CONFIG_VERSION_MAJOR 10
#define CONFIG_VERSION_MINOR 2
#define CONFIG_VERSION_PATCH 0
#define CONFIG_VERSION_BUILD "70eb038a2e-dirty"

#define CONFIG_VERSION ((CONFIG_VERSION_MAJOR << 16) |\
                        (CONFIG_VERSION_MINOR << 8) |\
                        (CONFIG_VERSION_PATCH))

#endif /* __INCLUDE_NUTTX_VERSION_H */
